const OTP_PURPOSES = Object.freeze({
  REGISTER: "REGISTER",
  RESET_PASSWORD: "RESET_PASSWORD",
});

const OTP_CHANNELS = Object.freeze({
  EMAIL: "EMAIL",
  PHONE: "PHONE",
});

const OTP_TTL_SECONDS = 5 * 60;
const OTP_RESEND_COOLDOWN_SECONDS = 30;
const OTP_MAX_ATTEMPTS = 5;
const OTP_MAX_REQUESTS_PER_HOUR = 5;

module.exports = {
  OTP_CHANNELS,
  OTP_MAX_ATTEMPTS,
  OTP_MAX_REQUESTS_PER_HOUR,
  OTP_PURPOSES,
  OTP_RESEND_COOLDOWN_SECONDS,
  OTP_TTL_SECONDS,
};
